### ISSUE TITLE
Installing Gauge plugin for Eclipse has artifact not found

### ISSUE THREAD

**Issue by teseu** [getgauge/Gauge-Eclipse#22]
I was trying a fresh installation for a shared machine and I came across this problem. Several artifacts could not be found, the URL appears to be wrong, or out of date. One example is:
https://dl.bintray.com/gauge/Gauge/plugins/com.thoughtworks.gauge.eclipse_0.0.3.jar

And the installation of the plugin cannot be completed.

The full stack:
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: https://dl.bintray.com/gauge/Gauge/plugins/com.thoughtworks.gauge.eclipse_0.0.3.jar.
https://dl.bintray.com/gauge/Gauge/plugins/com.thoughtworks.gauge.eclipse_0.0.3.jar
Artifact not found: https://dl.bintray.com/gauge/Gauge/plugins/io.getgauge_0.0.3.jar.
https://dl.bintray.com/gauge/Gauge/plugins/io.getgauge_0.0.3.jar
Artifact not found: https://dl.bintray.com/gauge/Gauge/features/io.getgauge.sdk_0.0.3.jar.
https://dl.bintray.com/gauge/Gauge/features/io.getgauge.sdk_0.0.3.jar
Artifact not found: https://dl.bintray.com/gauge/Gauge/plugins/io.getgauge.ui_0.0.3.jar.
https://dl.bintray.com/gauge/Gauge/plugins/io.getgauge.ui_0.0.3.jar

**Comment by kashishm** [comment]
The URL of Gauge Eclipse plugin update site has been changed to https://dl.bintray.com/gauge/Gauge-Eclipse.
Thanks for pointing this out, we have updated the documentation.

**Comment by teseu** [comment]
Thanks for the quick response Kashishm, I guess this issue can be closed now, right?

**Comment by mahendrakariya** [comment]
Yup! Closing this issue.
